### ISSUE TITLE
"width" option not working correctly

### ISSUE THREAD

**Issue by MrAlexWeber** [madnight/bitcoin-chart-cli#10]
Hello, first of all, great app here!
I installed on my Mac (macOS 10.12.6) and I noticed some strange behavior trying to set the 'width' option.
For -w 70 and -w 80, it seems like the chart is displayed at the same width, and only the text underneath the chart changes its width. Image attached.

![image](https://user-images.githubusercontent.com/463469/34226525-c89ebb3a-e57e-11e7-8489-b4f2a6a992ff.png)

**Comment by madnight** [comment]
@MrAlexWeber i'll check that, i guess i should be able improve the width calculation

**Comment by madnight** [comment]
Okay should be better now, you can test:
`npm remove bitcoin-chart-cli -g && npm install -g bitcoin-chart-cli --upgrade`
you should then have `bitcoin-chart-cli --version` 3.2.2

**Comment by MrAlexWeber** [comment]
Wow, talk about support! That seems to have fixed it. Thank you!
