### ISSUE TITLE
Sorry. The coin/currency pair BTC/USD does not exist in the cryptocompare api.

### ISSUE THREAD

**Issue by haihosilver** [madnight/bitcoin-chart-cli#11]
```
$ npm install bitcoin-chart-cli -g
$ bitcoin-chart-cli
Sorry. The coin/currency pair BTC/USD does not exist in the cryptocompare api.
$ bitcoin-chart-cli --coin ETH -d 360 -w 80 -h 20
Sorry. The coin/currency pair ETH/USD does not exist in the cryptocompare api.
```

**Comment by madnight** [comment]
Yup, seems to be a temporary problem with the API https://www.cryptocompare.com/.
As for example: https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=BTC,USD,EUR 
"This site can’t be reached"

Lets wait a bit and see if the API is going to work again soon. Otherwise i will search for a new API.

**Comment by kroitor** [comment]
@madnight I would suggest coinmarketcap, it's is available in [ccxt](https://github.com/ccxt/ccxt) as well as many other exchanges. Hope it helps!

**Comment by madnight** [comment]
It seems as though the whole website https://www.cryptocompare.com/ is temporary down.
![](https://i.imgur.com/q15zMN6.png)

I'll give it a bit more time to recover, because the API is very good and was very reliable until yesterday.

**Comment by madnight** [comment]
OK they are back online for the moment, lets see

**Comment by madnight** [comment]
https://coinmarketcap.com/api/

Historical Data
* Coming Soon

@kroitor coinmarketcap does not have historical data yet, but when this gets released i will add coinmarketcap as a fallback API, so that in case of a cryptocompare downtime the coinmarketcap API will be used

**Comment by asymmetric** [comment]
Happens to me only with `--width 30`.

**Comment by madnight** [comment]
@asymmetric which terminal and which operating system do you use?
`bitcoin-chart-cli --width 30` works for me

**Comment by asymmetric** [comment]
`watch -n60 bitcoin-chart-cli --mins 60 --width 30 -c BTC` does not work for example, changing to 60 does.

Don't think the terminal matters tbh, but it's alacritty. bitcoin-chart-cli version 3.2.2.

**Comment by madnight** [comment]
https://github.com/madnight/bitcoin-chart-cli/issues/23
