### ISSUE TITLE
Empty chart when using bitcoin-chart-cli with watch

### ISSUE THREAD

**Issue by robooo** [madnight/bitcoin-chart-cli#14]
bitcoin-chart-cli works without any problems (tried all args, resizing terminal etc.), but after using 
`watch bitcoin-chart-cli...` I see just numbers, header, info but no chart, the whole screen is empty

Using OS X, iterm2, node = 9.4.0

**Comment by madnight** [comment]
Hmm maybe there is a difference between the OS X watch command and the Linux one? Usually i would expect that watch just calls the command over an over again, not sure why this could possibly go wrong. You could try to use a bash loop instead of watch.

**Comment by robooo** [comment]
Yes I fixed it already with 
` while :; do clear; bitcoin-chart-cli; sleep 15; done`
