### ISSUE TITLE
Support for api key?

### ISSUE THREAD

**Issue by TexZeTech** [madnight/bitcoin-chart-cli#22]
I would like to use an api key from cryptopian just so I'm not limited to "free"

**Comment by madnight** [comment]
What kind of limitations does bitcoin-chart-cli have with the free api version?

**Comment by TexZeTech** [comment]
I'm going to mark this as closed I had a second copy of my script hitting there servers at a stupid rate. Sorry for wasting your time.

**Comment by TexZeTech** [comment]
so just refreshing four windows at 1min intervles results in 

`Sorry. The coin/currency pair BTC/CAD does not exist in the cryptocompare api.`

`{"Response":"Error","Message":"You are over your rate limit please upgrade your account!","HasWarning":false,"Type":99,"RateLimit":{"calls_made":{"second":1,"minute":1,"hour":1,"day":106,"month":75771,"total_calls":75771},"max_calls":{"second":20,"minute":300,"hour":3000,"day":10000,"month":75000}},"Data":{}}
`

So I will request the ability for an api key entry once again.

**Comment by madnight** [comment]
Should work with the newest version:

```
export CRYPTOCOMPARE_API_KEY=your_api_key
npx bitcoin-chart-cli@3.3.4
```
