### ISSUE TITLE
Provide option for user defined coins

### ISSUE THREAD

**Issue by madnight** [madnight/bitcoin-chart-cli#5]
@BlkChockr suggested that the user should be able to define any coin in an generic way by adding its code as param

`bitcoin-chart-cli --coin ETH`

**Comment by kroitor** [comment]
```JavaScript
"use strict";
let coin = null
process.argv.forEach (x => {
    if (x.indexOf ('--coin') >= 0)
        coin = x.split ('=')[1]
})
console.log (coin)
```

**Comment by madnight** [comment]
@kroitor thx, i think i need to rewrite it a bit, my linter settings are quite strong (no mutation allowed / only immutable values (const))

**Comment by kroitor** [comment]
```JavaScript
"use strict";
const coin = (process.argv.filter (x => x.indexOf ('--coin') >= 0)[0] || '--coin=default').split ('=')[1]
console.log (coin)
```

**Comment by madnight** [comment]
done! version 3.0 released 
thx to @kroitor and @BlkChockr

**Comment by kroitor** [comment]
Cool! )
